name: DocFX Build
on:
  push:
    branches:
      - release/latest
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Check out the branch that triggered this workflow to the 'source' subdirectory
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: source
          ref: release/latest
      # Run a build
      - name: Build docs
        run: "& ./eng/common/build.ps1 -restore -build -projects ./docs/docfx/docfx.csproj"
        working-directory: ./source
